local addon, tbl = ...

local classDefaults = {
	["Death Knight"] = {
		["Armor"] = tbl.L["PLATE"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 1,
			["Daggers"] = 0,
			["Fist Weapons"] = 0,
			["Two-Handed Axes"] = 1,
			["Two-Handed Swords"] = 1,
			["Two-Handed Maces"] = 1,
			["Staves"] = 0,
			["Polearms"] = 1,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 0,
			["Shield"] = 0,
		},
	},
	["Demon Hunter"] = {
		["Armor"] = tbl.L["LEATHER"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 0,
			["Daggers"] = 0,
			["Fist Weapons"] = 1,
			["Two-Handed Axes"] = 0,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 0,
			["Staves"] = 0,
			["Polearms"] = 0,
			["Warglaives"] = 1,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 0,
			["Shield"] = 0,
		},
	},
	["Druid"] = {
		["Armor"] = tbl.L["LEATHER"],
		["Weapons"] = {
			["One-Handed Axes"] = 0,
			["One-Handed Swords"] = 0,
			["One-Handed Maces"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Two-Handed Axes"] = 0,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 1,
			["Staves"] = 1,
			["Polearms"] = 1,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 0,
			["Shield"] = 0,
		},
	},
	["Hunter"] = {
		["Armor"] = tbl.L["MAIL"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 0,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Swords"] = 1,
			["Two-Handed Maces"] = 0,
			["Staves"] = 1,
			["Polearms"] = 1,
			["Warglaives"] = 0,
			["Bow"] = 1,
			["Crossbow"] = 1,
			["Gun"] = 1,
			["Wand"] = 0,
			["Shield"] = 0,
		},
	},
	["Mage"] = {
		["Armor"] = tbl.L["CLOTH"],
		["Weapons"] = {
			["One-Handed Axes"] = 0,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 0,
			["Daggers"] = 1,
			["Fist Weapons"] = 0,
			["Two-Handed Axes"] = 0,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 0,
			["Staves"] = 1,
			["Polearms"] = 0,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 1,
			["Shield"] = 0,
		},
	},
	["Monk"] = {
		["Armor"] = tbl.L["LEATHER"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 1,
			["Daggers"] = 0,
			["Fist Weapons"] = 1,
			["Two-Handed Axes"] = 0,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 0,
			["Staves"] = 1,
			["Polearms"] = 1,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 0,
			["Shield"] = 0,
		},
	},
	["Paladin"] = {
		["Armor"] = tbl.L["PLATE"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 1,
			["Daggers"] = 0,
			["Fist Weapons"] = 0,
			["Two-Handed Axes"] = 1,
			["Two-Handed Swords"] = 1,
			["Two-Handed Maces"] = 1,
			["Staves"] = 0,
			["Polearms"] = 1,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 0,
			["Shield"] = 1,
		},
	},
	["Priest"] = {
		["Armor"] = tbl.L["CLOTH"],
		["Weapons"] = {
			["One-Handed Axes"] = 0,
			["One-Handed Swords"] = 0,
			["One-Handed Maces"] = 1,
			["Daggers"] = 0,
			["Fist Weapons"] = 0,
			["Two-Handed Axes"] = 0,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 0,
			["Staves"] = 1,
			["Polearms"] = 0,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 1,
			["Shield"] = 0,
		},
	},
	["Rogue"] = {
		["Armor"] = tbl.L["LEATHER"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Two-Handed Axes"] = 0,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 0,
			["Staves"] = 0,
			["Polearms"] = 0,
			["Warglaives"] = 0,
			["Bow"] = 1,
			["Crossbow"] = 1,
			["Gun"] = 1,
			["Wand"] = 0,
			["Shield"] = 0,
		},
	},
	["Shaman"] = {
		["Armor"] = tbl.L["MAIL"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 0,
			["One-Handed Maces"] = 0,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 1,
			["Staves"] = 1,
			["Polearms"] = 0,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 0,
			["Shield"] = 1,
		},
	},
	["Warlock"] = {
		["Armor"] = tbl.L["CLOTH"],
		["Weapons"] = {
			["One-Handed Axes"] = 0,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 0,
			["Daggers"] = 1,
			["Fist Weapons"] = 0,
			["Two-Handed Axes"] = 0,
			["Two-Handed Swords"] = 0,
			["Two-Handed Maces"] = 0,
			["Staves"] = 1,
			["Polearms"] = 0,
			["Warglaives"] = 0,
			["Bow"] = 0,
			["Crossbow"] = 0,
			["Gun"] = 0,
			["Wand"] = 1,
			["Shield"] = 0,
		},
	},
	["Warrior"] = {
		["Armor"] = tbl.L["PLATE"],
		["Weapons"] = {
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["One-Handed Maces"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Swords"] = 1,
			["Two-Handed Maces"] = 1,
			["Staves"] = 1,
			["Polearms"] = 1,
			["Warglaives"] = 0,
			["Bow"] = 1,
			["Crossbow"] = 1,
			["Gun"] = 1,
			["Wand"] = 0,
			["Shield"] = 1,
		},
	},
}

tbl.classDefaults = classDefaults