local addonName, addonTable = ...
local objects = {
	[35591] = PROFESSIONS_FISHING, 	-- Bobber: Normal
	[245190] = PROFESSIONS_FISHING, -- Bobber: Oversized
	[355518] = PROFESSIONS_FISHING, -- Bobber: Bat Visage
	[241593] = PROFESSIONS_FISHING, -- Bobber: Can of Worms
	[268886] = PROFESSIONS_FISHING, -- Bobber: Carved Wooden Helm
	[241594] = PROFESSIONS_FISHING, -- Bobber: Cat Head
	[268884] = PROFESSIONS_FISHING, -- Bobber: Demon Noggin
	[268883] = PROFESSIONS_FISHING, -- Bobber: Enchanted Bobber
	[268888] = PROFESSIONS_FISHING, -- Bobber: Face of the Forest
	[268885] = PROFESSIONS_FISHING, -- Bobber: Floating Totem
	[241596] = PROFESSIONS_FISHING, -- Bobber: Murloc Head
	[268887] = PROFESSIONS_FISHING, -- Bobber: Replica Gondola
	[241595] = PROFESSIONS_FISHING, -- Bobber: Squeaky Duck
	[241592] = PROFESSIONS_FISHING, -- Bobber: Tugboat
	[266869] = PROFESSIONS_FISHING, -- Bobber: Wooden Pepe
}
addonTable.objects = objects